### ISSUE TITLE
Frija has stopped working

### ISSUE THREAD

**Issue by aaazv** [wssyncmldm/frija#1]
It says Frija has stopped working on my windows 8.1 yoga 2 lenovo.
It stops right after download starts.
I have installed c++ 2008 to 2019
and .net 3.5 and 4.8
I don't know what else should I do

**Comment by wssyncmldm** [comment]
Hmm, that doesnt sound right.
There is no issue until Frija looks for update right?
Is there enough space in C drive or the drive you are saving firmware to?

**Comment by aaazv** [comment]
Yes. Enough capacity. I lost 50gb of data because I thought that the problem is with the sammobile file. At first, it was stopping after 10 seconds of working, changing the compatibility to win 7 and vista made it work till decryption, but at the end of decryption kept stopping again

**Comment by wssyncmldm** [comment]
That is weird though. I have tested it on Win 7, 8 and 10 and on various
different PC/Laptops. What I can do for you is build a debug app that will
let me help you debug the problem. You will possibly have to download
Visual studio however to be able to debug and help me find issue. Because
windows is weird about letting user know about the issue that made it
crash. Once I get home I will try to see if I can find an alternative to
downloading visual studio for debugging. I will contact you after I figure
out how to debug issue on remote computer like yours. Are you available on
anywhere else besides github? To be able to contact you easily?

**Comment by wssyncmldm** [comment]
No response or inactive OP
